###############################################################################
#
# Copyright 2006 by the <a href="http://spa-www.cs.umass.edu/">Scale Compiler Group</a>,<br>
# <a href="http://www.cs.umass.edu/">Department of Computer Science</a><br>
# <a href="http://www.umass.edu/">University of Massachusetts</a>,<br>
# Amherst MA. 01003, USA<br>
# All Rights Reserved.<br>
# <p>
# $Id: Makefile,v 1.1 2006-12-05 21:02:10 burrill Exp $
#
###############################################################################

PACKAGE    := scale/frontend/java
DEST       := $(CLASSDEST)/$(PACKAGE)

CLASSFILES :=	$(DEST)/SourceJava.class

MODULES :=

fortran: java


all: javaall

clean: javaclean

include $(SCALE)/$(SCALERELEASE)/scale/Makefile.defs
